#
# Use REST Client (VSCode extension) to test the API
#


#### Login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test1234"
}

#### Signup

POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test1234",
    "name": "Test User"
}